{
    "name" : "Hospital Management System",
    "author": "Aftab Boyz Solutions",
    "summary" : "Training Phase",
    "version" : "18.0.0.0",
    "license" : "LGPL-3",
    "depends" : [
        "mail",
        "product",
        "account",
        "sale",
        'report_xlsx',
        'custom_header_footer',
        'website',
    ], # Specifies that the module depends on the 'base' module
    'data': [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "data/patient_tag_data.xml",
        "data/patient.tag.csv",
        "data/mail_template_data.xml",
        "data/cron.xml",
        "wizard/cancel_appointment.xml",
        "wizard/appointment_example.xml",
        "views/patient_views_readonly.xml",
        "views/patient_appointment.xml",
        "views/patient_views.xml",
        "views/patient_tag_view.xml",
        "views/patient_appointment_line.xml",
        "views/doctor_view.xml",
        "views/doctor_specialize.xml",
        "views/account_views.xml",
        "views/technical_view.xml",
        "views/sale_order_view.xml",
        "views/menu.xml",
        "views/res_config_settings_views.xml",
        "views/templates.xml",
        "views/website_menu.xml",
        "report/patient_record.xml",
        "report/patient_card.xml",
        "report/example_appointment.xml",
        "report/doctor_card.xml",
        "report/sale_report_inherit.xml",
        "report/report.xml",
    ],
    'assets': {
    'web.report_assets_common': [
        '/hospital/static/src/img/patient.jpeg',
        ],
    },
    'application': True,  # This will make the module appear as an application in Odoo
    'installable': True,
    'auto_install': False,
}
