{
    'name': "Mobile Barcode/Qrcode Scanner widget: All in one",
    'version': '18.0.0.1',
    'depends': ['base'],
    'author': "Yatrik Chauhan",
    'category': "Sales/Sales",
    'summary': 'All in one: Barcode and QR code scanner widget | Scan barcode and QR code using mobile camera and webcam',
    'description': """
        All in one: Barcode and QR code scanner widget | Scan barcode and QR code using mobile camera and webcam
    """,
    'depends': ['web'],
    'price': 35,
    'currency': 'USD',
    "license": "LGPL-3",
    'live_test_url': 'https://youtu.be/DPPHqo23ZGs?si=tOn7fO-dxfv5fzEu',
    'assets': {
        'web.assets_backend': [
            "yc_code_scanner_mobile/static/src/css/webcam_qrcode_scan_styles.css",
            "yc_code_scanner_mobile/static/src/libs/html5-qrcode.min.js",
            "yc_code_scanner_mobile/static/src/libs/quagga.min.js",
            ('include', 'web._assets_core'),
            "yc_code_scanner_mobile/static/src/js/barcode_scanner_search_bar.js",
            "yc_code_scanner_mobile/static/src/js/boolean_scanner_field_widget.js",
            "yc_code_scanner_mobile/static/src/js/many2many_tags_code_scanner.js",
            "yc_code_scanner_mobile/static/src/xml/barcode_scanner_search_bar.xml",
            "yc_code_scanner_mobile/static/src/js/many2one_barcode_scanner.js",
            "yc_code_scanner_mobile/static/src/js/barcode_scanner_widget.js",
            "yc_code_scanner_mobile/static/src/xml/boolean_scanner_widget.xml",
            "yc_code_scanner_mobile/static/src/xml/many2many_tags_code_field.xml",
            "yc_code_scanner_mobile/static/src/xml/many2one_barcode_scanner.xml",
            "yc_code_scanner_mobile/static/src/xml/webcam_qrcode_scan_template.xml",
        ],
        'web._assets_core': [
            "yc_code_scanner_mobile/static/src/core/qrcode/code_configurator.js",
            "yc_code_scanner_mobile/static/src/core/qrcode/code_configurator.xml",
            "yc_code_scanner_mobile/static/src/core/qrcode/code_dialog.js",
            "yc_code_scanner_mobile/static/src/core/qrcode/code_dialog.xml",
        ],
    },
    'images': ['static/description/banner.gif'],
    'installable': True,
    'application': True,
    'auto_install': False,
}