from . import patient
from . import appointment
from . import patient_tag
from . import doctor
from . import account_move
from . import technical
from . import res_config_settings
from . import sale_order
from . import sale_report